### ISSUE TITLE
Variable names with brackets in xcsp2mzn compiler

### ISSUE THREAD

**Issue by lingmar** [CP-Unibo/mzn2feat#1]
I have a bunch of files in XCSP2.1 format containing variables named x[0], x[1], ... etc. These variable names cause a syntax error in MiniZinc (where x is interpreted as a non-declared array). I am not sure whether the issue lies in the xcsp2mzn compiler or in my files; I'm not an expert so I can't tell if this variable name format is actually allowed in XSCP2.1.

Anyway, I could solve the problem by by simply removing the brackets (in xcsp2mzn.cc, variables like "x[0]" are renamed to "x0"). I could submit a pull request if you want, but if you decide to fix this, maybe you guys who know the code better than me want to do your own tweak.

Best,
Linnea

**Comment by ramadini** [comment]
Hi Lingmar! Thanks for reporting the issue.

I'm not an expert of XCSP 2.1 either (btw,  I think now they switched to XCSP 3: http://www.xcsp.org/format3.pdf). Are those variables x[k] defined "standalone" in the XCSP model or do they refer to a collection of variables x? If you are not sure you can send us the XCSP source. 

Best,

Roberto.

**Comment by lingmar** [comment]
As far as I can see, they are standalone and not referring to some collection of variables x. Just ordinary variables named like x[k]. 

The collection of XCSP models (compressed with lzma) I use can be found at https://bitbucket.org/pschaus/xp-table. See for example xp-table/instances/randsJC10000/rand-7-40-8-40-10000-0.xml.

Here is a small snippet from that file:

`<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<instance>
  <presentation format="XCSP 2.1" maxConstraintArity="7" type="CSP"/>
  <domains nbDomains="1">
    <domain name="D0" nbValues="8">0..7</domain>
  </domains>
  <variables nbVariables="40">
    <variable domain="D0" name="x[0]"/>
    <variable domain="D0" name="x[1]"/>
    <variable domain="D0" name="x[2]"/>...`

which compiles into:

`% Processing instance<instance>
include "table.mzn";
include "cumulative.mzn";
include "disjunctive.mzn";
include "element.mzn";
include "alldifferent.mzn";
% Start processing domains
set of int: D0 =  0..7;
% Domains processed
% Start processing variables
var D0: x[0];
var D0: x[1];
var D0: x[2];
...`

**Comment by jacopoMauro** [comment]
Hi Lingmar.

Based on the specification of XCSP 2.1 the identifiers are defined as follows:
<identifier> ::= <letter> | "_" { <letter> | <digit> | "_" }
<integer> ::= [ "+" | "-"] <digit> {<digit>}
<letter> ::= "a".."z" | "A".."Z"
<digit> ::= "0".."9"

Therefore I do not think that "x[0]" name is a valid name in XCSP.
If I were you I would change the names removing the square brakes with underscores. That should do the trick.

Best,
Jacopo

**Comment by lingmar** [comment]
Ok, thank you! 
And thanks for providing this compiler!

Best,
Linnea
