### ISSUE TITLE
mzn2fzn is no longer provided by minizinc

### ISSUE THREAD

**Issue by felixvuo** [CP-Unibo/mzn2feat#3]
The command mzn2fzn is no longer provided In recent versions of minizinc - instead users are instructed to use the minizinc binary itself.  This is easily fixed with a symbolic link in MINIZINC/bin, but it would be nice if mzn2feat could work "out of the box".

PS Thank you for making this tool - I am hoping it will help as I am beginning my PhD investigations.

**Comment by ramadini** [comment]
Hi Felix, thanks for you feedback. This tool was developed more than 5 years ago and unfortunately no longer maintained.... However, pull requests are welcome of course!
P.S. Good luck with your PhD! What is that about?
